# env.sh
# Default environment variables for your dev environment.
# DO NOT EDIT THIS FILE FOR LOCAL CHANGES.
# Instead, create an 'env.local.sh' file and override variables there.

## Features (Disabled by default)
export ENABLE_DOTFILES_FZF_CTRL_T=0     # Set to 1 in env.local.sh to enable
export ENABLE_AUTO_WORKSPACE_ENV=0      # Set to 1 in env.local.sh to enable
export ENABLE_CUSTOM_PROMPT=0           # Set to 1 in env.local.sh to enable

## Feature Options (Defaults)
export PROMPT_USER_LABEL="USER"